// src/ai/MessageAnalyzer.js

class MessageAnalyzer {
  constructor() {
      this.riskKeywords = {
            high: ['kill', 'hurt', 'die', 'suicide', 'rape', 'beat', 'stab', 'threat'],
                  medium: ['stupid', 'worthless', 'ugly', 'fat', 'no one loves you', 'useless'],
                        low: ['shut up', 'dumb', 'crazy', 'dramatic']
                            };
                                
                                    this.manipulationPatterns = [
                                          'if you loved me',
                                                'no one else will',
                                                      'you owe me',
                                                            'I will kill myself if you leave'
                                                                ];
                                                                  }

                                                                    // Advanced AI analysis with multiple risk factors
                                                                      analyzeMessage(text) {
                                                                          const analysis = {
                                                                                riskLevel: 'low',
                                                                                      riskScore: 0,
                                                                                            detectedPatterns: [],
                                                                                                  warnings: [],
                                                                                                        confidence: 0.8
                                                                                                            };

                                                                                                                // Convert to lowercase for analysis
                                                                                                                    const lowerText = text.toLowerCase();

                                                                                                                        // Check for high-risk keywords
                                                                                                                            this.riskKeywords.high.forEach(keyword => {
                                                                                                                                  if (lowerText.includes(keyword)) {
                                                                                                                                          analysis.detectedPatterns.push(`Threatening language: "${keyword}"`);
                                                                                                                                                  analysis.riskScore += 30;
                                                                                                                                                        }
                                                                                                                                                            });

                                                                                                                                                                // Check for medium-risk keywords
                                                                                                                                                                    this.riskKeywords.medium.forEach(keyword => {
                                                                                                                                                                          if (lowerText.includes(keyword)) {
                                                                                                                                                                                  analysis.detectedPatterns.push(`Verbal abuse: "${keyword}"`);
                                                                                                                                                                                          analysis.riskScore += 15;
                                                                                                                                                                                                }
                                                                                                                                                                                                    });

                                                                                                                                                                                                        // Check for manipulation patterns
                                                                                                                                                                                                            this.manipulationPatterns.forEach(pattern => {
                                                                                                                                                                                                                  if (lowerText.includes(pattern)) {
                                                                                                                                                                                                                          analysis.detectedPatterns.push(`Emotional manipulation: "${pattern}"`);
                                                                                                                                                                                                                                  analysis.riskScore += 20;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                // Sentiment analysis (simplified)
                                                                                                                                                                                                                                                    const negativeWords = ['hate', 'stupid', 'ugly', 'worthless', 'disgusting'];
                                                                                                                                                                                                                                                        const positiveWords = ['love', 'beautiful', 'smart', 'proud'];
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                let sentimentScore = 0;
                                                                                                                                                                                                                                                                    negativeWords.forEach(word => {
                                                                                                                                                                                                                                                                          if (lowerText.includes(word)) sentimentScore--;
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                  positiveWords.forEach(word => {
                                                                                                                                                                                                                                                                                        if (lowerText.includes(word)) sentimentScore++;
                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                if (sentimentScore < -2) {
                                                                                                                                                                                                                                                                                                      analysis.warnings.push('Highly negative sentiment detected');
                                                                                                                                                                                                                                                                                                            analysis.riskScore += 10;
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    // Determine overall risk level
                                                                                                                                                                                                                                                                                                                        if (analysis.riskScore >= 40) {
                                                                                                                                                                                                                                                                                                                              analysis.riskLevel = 'high';
                                                                                                                                                                                                                                                                                                                                  } else if (analysis.riskScore >= 20) {
                                                                                                                                                                                                                                                                                                                                        analysis.riskLevel = 'medium';
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                // Calculate confidence based on pattern matches
                                                                                                                                                                                                                                                                                                                                                    analysis.confidence = Math.min(0.95, 0.7 + (analysis.detectedPatterns.length * 0.1));

                                                                                                                                                                                                                                                                                                                                                        return analysis;
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                            // AI-powered pattern recognition across multiple messages
                                                                                                                                                                                                                                                                                                                                                              analyzeConversation(messages) {
                                                                                                                                                                                                                                                                                                                                                                  const conversationAnalysis = {
                                                                                                                                                                                                                                                                                                                                                                        overallRisk: 'low',
                                                                                                                                                                                                                                                                                                                                                                              escalationDetected: false,
                                                                                                                                                                                                                                                                                                                                                                                    recurringPatterns: [],
                                                                                                                                                                                                                                                                                                                                                                                          safetyRecommendations: []
                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                  let totalRiskScore = 0;
                                                                                                                                                                                                                                                                                                                                                                                                      let riskTrend = [];

                                                                                                                                                                                                                                                                                                                                                                                                          messages.forEach((message, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                const messageAnalysis = this.analyzeMessage(message.text);
                                                                                                                                                                                                                                                                                                                                                                                                                      totalRiskScore += messageAnalysis.riskScore;
                                                                                                                                                                                                                                                                                                                                                                                                                            riskTrend.push(messageAnalysis.riskScore);

                                                                                                                                                                                                                                                                                                                                                                                                                                  // Detect recurring patterns
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (messageAnalysis.detectedPatterns.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                conversationAnalysis.recurringPatterns.push(...messageAnalysis.detectedPatterns);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Check for escalation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (riskTrend.length >= 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const recentTrend = riskTrend.slice(-3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (recentTrend[2] > recentTrend[1] && recentTrend[1] > recentTrend[0]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversationAnalysis.escalationDetected = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              conversationAnalysis.safetyRecommendations.push('Warning: Escalating behavior detected. Consider increasing safety measures.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Overall risk assessment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const averageRisk = totalRiskScore / messages.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (averageRisk >= 30) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          conversationAnalysis.overallRisk = 'high';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conversationAnalysis.safetyRecommendations.push('High-risk conversation patterns detected. Please seek support.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (averageRisk >= 15) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          conversationAnalysis.overallRisk = 'medium';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conversationAnalysis.safetyRecommendations.push('Concerning patterns detected. Monitor the situation.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return conversationAnalysis;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Multilingual support placeholder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async translateForAnalysis(text, targetLanguage = 'en') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // In a real implementation, this would integrate with translation APIs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            originalText: text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  translatedText: text, // Placeholder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        translationConfidence: 0.8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              detectedLanguage: 'en'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default new MessageAnalyzer();